Add types for safe apps access control property and `clientUrl` param to the query
gnosis/safe-react-gateway-sdk pull request #51
Opened 2022-01-06 15:10 UTC by mikheevm

This is needed for https://github.com/gnosis/safe-react/issues/2672. The properties are live on staging config service, the PR to the client gateway is still open.

Ready to merge after https://github.com/gnosis/safe-client-gateway/pull/774

2022-01-06 19:46 UTC, katspaugh commented on src/types/safe-apps.ts
> +  type: 'DOMAIN_ALLOWLIST'
Might be worth exporting the possible types as an enum, so that in the react app you can branch based on the type?

2022-01-06 19:46 UTC, katspaugh approved these changes
Nice! Just one suggestion.

2022-01-07 08:30 UTC, iamacook commented on src/types/safe-apps.ts
> +  type: 'DOMAIN_ALLOWLIST'
This would be my only suggestion as well.

2022-01-07 10:59 UTC, mikheevm commented on src/types/safe-apps.ts
> +  type: 'DOMAIN_ALLOWLIST'
brainfart sers, thanks for noticing

2022-01-07 11:08 UTC, iamacook approved these changes
🚀

2022-01-07 11:13 UTC, katspaugh requested changes
There's some dump file committed.
Please also update the version in package.json so that I can publish the package.

2022-01-07 13:06 UTC, katspaugh approved these changes
Thhhhhhanks!

2022-01-10 15:39 UTC, iamacook approved these changes

2022-01-10 18:01 UTC, merged